### ISSUE TITLE
Using Fedora, theme is not in the list after installation

### ISSUE THREAD

**Issue by tonyrulez** [SylEleuth/smplayer-gruvbox#1]
Hi,

I installed the theme, however after restarting SMPlayer, the theme is not in the dropdown list.
I'm using Fedora and smplayer was installed using dnf. Any idea why the theme isn't recognized by smplayer?

```
tonyrulez@192:~/.config/smplayer/themes$ ll
drwxr-xr-x tonyrulez tonyrulez  36 B  Thu Jul  7 17:28:50 2022  ./
drwxrwxr-x tonyrulez tonyrulez 244 B  Thu Jul  7 17:29:49 2022  ../
drwxr-xr-x tonyrulez tonyrulez 4.4 KB Thu Jul  7 17:08:04 2022  Gruvbox/
.rw-r--r-- tonyrulez tonyrulez 6.2 KB Thu Jul  7 17:08:04 2022  Gruvbox.qrc
```

**Comment by SylEleuth** [comment]
Hi.

Sorry for a delay. I haven't been on github for some time.

I'm sorry but I don't know why it's not working. I'm not using Fedora and recently moved to Arch, but I don't believe it shouldn't work the same. I doubt that Fedora is doing something differently, folder structure is the same. I should install Fedora in VM and test it there, but currently I can't. When I will find a time I will share what I found.

In the meantime can You tell me what is Your version of SMPlayer? And have You installed themes (it's separated package)? Do they show up in drop down menu?

**Comment by tonyrulez** [comment]
Hi,

don't know what happened, but after an smplayer update Gruvbox showed up under the Icon Sets :+1:
